name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:ci

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: junit.xml

  e2e:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run E2E tests
      run: npm run test:e2e

  load-test:
    needs: e2e
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install k6
      run: |
        curl -L https://github.com/grafana/k6/releases/download/v0.45.0/k6-v0.45.0-linux-amd64.tar.gz -o k6.tar.gz
        tar xzf k6.tar.gz
        sudo mv k6-v0.45.0-linux-amd64/k6 /usr/local/bin

    - name: Run load tests
      run: k6 run tests/load/load-test.js
